import ReactQueryProvider from "@/providers/ReactQueryProvider";
import RecoilProviders from "@/providers/RecoilProvider";
import type { Metadata } from "next";
import { Inter, Jua } from "next/font/google";
import "../styles/globalStyle.scss";

const inter = Inter({ subsets: ["latin"] });

const JuaR = Jua({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilProviders>
      <html lang="en">
        <body className={JuaR.className}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </body>
      </html>
    </RecoilProviders>
  );
}
